
  
#-----------------------------------------
# CloudBuild Pipeline for Staging CloudRun
#-----------------------------------------
steps:
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   args: ['echo', 'Building...']
   id  : BUILD

 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   args: ['echo', 'Testing...']
   id  : TEST

 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   args:
    - gcloud
    - functions
    - deploy
    - $_FUNCTION_NAME
    - --region=&_FUNCTION_REGION
    - --source=.
    - --trigger-http
    - --runtime=$_FUNCTION_RUNTIME
    - --project=$_FUNCTION_PROJECT
    - --entry_point=$_ENTRY_POINT
    id  : DEPLOY



substitutions: 
    _FUNCTION_PROJECT : staging
    _FUNCTION_NAME    : puthon_app
    _FUNCTION_REGION  : europe-central2
    _FUNCTION_RUNTIME : Python 3.8 
    _ENTRY_PONT       : hello_world
